name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubernetes context
        run: |
          az aks get-credentials --resource-group myResourceGroup --name myAKSCluster

      - name: Check kubectl version
        run: kubectl version --client

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Force rollout restart
        run: kubectl rollout restart deployment/my-flask-app

      - name: Get Application URL
        run: |
          APP_URL=$(kubectl get svc my-flask-app-service -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          echo "Application URL: ${APP_URL}"
